# Generated by Django 3.0.5 on 2020-09-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Experiência'),
        ),
    ]
