# Generated by Django 3.0.5 on 2020-09-16 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pokemon_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonteam',
            name='trainer',
            field=models.ManyToManyField(related_name='trainer_pokemon', to=settings.AUTH_USER_MODEL),
        ),
    ]
